# Generated by Django 4.2.7 on 2024-02-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('PROGRAMMING', 'programming'), ('COMPUTER SCIENCE', 'computer science'), ('MATHEMATICS', 'mathematics'), ('PORTUGUESE', 'portuguese'), ('ENGLISH', 'english'), ('LEGISLATION', 'legislation'), ('NOT SPECIFIED', 'not specified')], default='NOT SPECIFIED', max_length=100),
        ),
    ]
